name: .NET Core Build CI

on:
  push:
    branches: [ "main", "master" ] # Altere se a sua branch principal tiver outro nome
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Faz o checkout do código do repositório para a máquina virtual
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Instala o SDK do .NET 10.0 necessário para o seu projeto
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    # 3. Restaura as dependências (Packages do NuGet) apontando para a pasta correta
    - name: Install dependencies
      run: dotnet restore ProjetoAWS/ProjetoAWS.csproj

    # 4. Compila o projeto sem fazer o deploy
    - name: Build project
      run: dotnet build ProjetoAWS/ProjetoAWS.csproj --configuration Release --no-restore
